# Generated by Django 5.1.3 on 2024-12-11 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('toxic', models.BooleanField(default=False)),
                ('toxic_probability', models.FloatField(default=0.0)),
                ('severe_toxic', models.BooleanField(default=False)),
                ('severe_toxic_probability', models.FloatField(default=0.0)),
                ('obscene', models.BooleanField(default=False)),
                ('obscene_probability', models.FloatField(default=0.0)),
                ('threat', models.BooleanField(default=False)),
                ('threat_probability', models.FloatField(default=0.0)),
                ('insult', models.BooleanField(default=False)),
                ('insult_probability', models.FloatField(default=0.0)),
                ('identity_hate', models.BooleanField(default=False)),
                ('identity_hate_probability', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Text Analysis',
                'verbose_name_plural': 'Text Analyses',
                'db_table': 'moderation_textanalysis',
                'ordering': ['-created_at'],
            },
        ),
    ]
